config/routes.rb
Bigblockdeals::Application.routes.draw do

  # This is for the Basic pages and their edit pages
  BASIC_CONTROLLERS.each do |f|
      get "#{f.last[:url].to_sym}/(:format)", :controller => "basics", :action => "#{f.first}", :as => f.last[:url]
      get "admin/#{f.last[:url].to_sym}/edit/(:id)(:format)", :controller => "basic_edits", :action => "#{f.first}", :as => "#{f.first}_edit"
      match "admin/#{f.last[:url].to_sym}/create/(:id)(:format)", :controller => "basic_edits", :action => "#{f.first}_create", :as => "#{f.first}_create"
  end
  match "business_inquires" => "business_leads#index"
  match "/business_leads/index" => "business_leads#index"

  root :to => "basics#current_deals"


  # This is for all the Good Reads
    get '/admin/good_reads/new' => "good_reads#new", :as => "new_good_read"
    get '/admin/good_reads/:id/edit' => "good_reads#edit", :as => "edit_good_read"
    get '/good_reads/category/:id', :controller => 'good_reads', :action => 'show_categories', :as => "good_reads_category"
    match "/good_reads/date" => redirect("/good_reads") 
    get '/good_reads/date/(:year(/:month))', :controller => 'good_reads', :action => 'show_dates', :as => "good_reads_date"
    resources :good_reads
    
  # This is for all the Quotes

    
    scope "admin" do
      resources :quotes, :as => "quotes"
      resources :widgets, :as => "widgets"
      match 'widgets/move_dim_widgets' => 'widgets#move_dim_widgets', :as => :move_dim_widgets
      resources :categories, :as => "categories"
      resources :sessions, :as => "sessions"
      resources :spreadsheets, :as => "spreadsheets"
      resources :affiliates, :as => "affiliates"
      # resources :business_leads, :as => "business_leads"
    end
    
  #this is for all the Catagories for the good reads

  # This is for the Administration usage.
    resources :admins
    
  # This is for loggin in and out
    get '/admin/login' => 'sessions#new', :as => "login"
    get '/admin/logout' => 'sessions#destroy', :as => "logout"
    get "/admin/business_lead/:id" => "business_leads#show", :as => "admin_business_lead"
    get "/admin/business_leads/" => "business_leads#show_all", :as => "admin_business_leads"
    match '/admin/business_leads/destroy/:id' => 'business_leads#destroy'
    
end

app/views/layouts/_admin_nav.html.erb
<!--
	TODO Add in Edit Widgets on current page if widgets are acceptable
-->

<% if session[:admin_id] %>
	<div id="admin_nav">
		<div id="admin-nav-container">
			<%= link_to "New Good Read", new_good_read_path %> <%= link_to "See Admins", admins_path %>
			<%= link_to "Manage Spreadsheets", spreadsheets_path %>
			<%= link_to "Manage Widgets", widgets_path %>
			<%= link_to "Manage Quotes", quotes_path() %>
			<%= link_to "Manage Business Inquiries", admin_business_leads_path() %>
			<%= link_to "Logout", logout_path %>
		</div>
	</div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if flash %>
	<div id="flash-notice-container">
		<% flash.each do |name, msg| %>
		  	<%= content_tag :div, msg, :id => "flash_#{name}", :class => "flash-notice-box" %>
			<a id="flash-notice-closer" href="#">×</a>
		<% end %>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<div id="footer-container">
	<div id="footer-topper"></div>
	<div id="footer">
		
		<ul id="useful-links">
			<h2 class="cafeta full-width-clearer">Useful Links</h2>
			<li><%= link_to 'About Us', :about_us, :class => "footer-link" %></li>
			<li><%= link_to 'Contact', :contact, :class => "footer-link" %></li>
			<li><%= link_to 'Terms of Service', :terms_of_service, :class => "footer-link" %></li>
			<li><%= link_to 'Policy', :privacy_policy, :class => "footer-link" %></li>
			<li><a class="footer-link" href="http://twitter.com/bigblockdeals" target="blank">Twitter</a></li>
			<li><a class="footer-link-last" href="http://facebook.com/bigblockdeals" target="blank">Facebook</a></li>
			<li class="footer-link">Copyright 2011 Big Block Deals</li>
			<img src="/images/footer-divider.png"/>
		</ul>
		
		<div id="recommendations">
			<h2 class="cafeta full-width-clearer">Recommendations?</h2>
			<span class="recommendation-text">Know a company that offers</span>
			<img src="/images/bottom-all-icons.png">
			<span class="recommendation-text bottom-rec-text">services?</span>
			<div class="full-width-clearer">
				<%= link_to 'Contact Us', :contact, :class => "recommendation-text" %><span class="recommendation-text"> and let us know!</span>
			</div>
		</div>
		
		<img id="footer-glare" src="/images/footer-glare.png"/>
		
	</div>
</div>

app/views/layouts/_main_nav.html.erb
<div id="nav-container">
	<div id="navigation">
		<h1 id="root-link"><a href="/">root</a></h1>
		<ul id="minor-nav">
			<li class="minor-link"><a href="/blog">Good Reads</a></li>
			<li class="minor-link"><a href="http://twitter.com/bigblockdeals" target="blank">Twitter</a></li>
			<li class="minor-link"><a href="http://facebook.com/bigblockdeals">Facebook</a></li>
			<li class="minor-link"><a href="/contact">Contact</a></li>
			<li class="minor-link"><a href="/about-us">About Us</a></li>
		</ul>
		<ul id="greater-nav">
			<li class="greater-nav-item"><a id="today-link" href="/today-deal"></a></li>
			<li class="greater-nav-item"><a id="recent-deals" href="/recent-deals"></a></li>
			<li class="greater-nav-item"><a id="how-it-works" href="/how-it-works"></a></li>
			<li class="greater-nav-item"><a id="business-link" href="/for-businesses"></a></li>
			<li class="greater-nav-item"><a id="login-link" href="#"></a></li>
		</ul>
		<div id="login-dropdown">
		
		</div>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<div id="nav-container">
	<div id="navigation">
		<h1 id="root-link"><a href="/">root</a></h1>
		
		<table id="greater-nav">
			<tr>
				<td class="greater-nav-item"><%= link_to 'Today\'s Deal', :root, :id => 'today-link' %></td>
				<td class="greater-nav-item"><%= link_to 'Recent Deals', :recent_deals %></td>
				<td class="greater-nav-item"><%= link_to 'How It Works', :how_it_works_consumers %></td>
				<td class="greater-nav-item"><%= link_to 'For Businesses', :for_businesses %></td>
				<td class="greater-nav-item"><%= link_to 'BBD Blog', good_reads_path %></td>
				<td class="greater-nav-item"><a href="javascript:void(0);" id="mydeals" onclick="javascript:showMyDeals();">My Account</a></td>
				<td class="greater-nav-item" id="login"></td>
			</tr>
		</table>
		</ul>
	</div>
</div>

app/views/layouts/_quotes.html.erb
<% if @active_quotes.any? %>
<div id="quote-container" class="hidden">
	
	<a href="#" id="quote-closer">×</a>
	<div id="all-quotes">
		<% @active_quotes.each do |f| %>
			<div class="indiv-quote">
				<p class="main-quote-text"><%= f.words_of_wisdom %></p>
				<p class="main-quote-author"> - <%= f.author %></p>
			</div>
		<% end %>
	</div>
	
	<div id="controls">
		<a href="#" class="quote-left-btn prev"></a>
		<a href="#" class="quote-right-btn next"></a>
	</div>

</div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
	<% if @page == "good_read" %>
	<p>test</p>
		<%= render 'good_reads/categories' %>
		<%= render 'good_reads/dates' %>
	<% else %>
		<%= render 'layouts/widgets' %>
	<% end %>
</div>

app/views/layouts/_sidebar_email_form.html.erb
<img src="/images/sidebar-signup-title.jpg"/>
<form class="sidebar-form">
	<label>Email</label>
	<input value="" name="email" type="text"></input>
	<label>ZIP</label>
	<input value="" name="ZIP" type="text"></input>
	<input class="submit-btn" value="Let's do this!" name="submit" type="submit"></input>
</form>

app/views/layouts/_widgets.html.erb
<% if session[:admin_id] %>
<!-- LOGGED IN WIDGET VIEWS -->
<% form_tag(move_dim_widgets_path, :method => "post") do %>

<ul id="sidebar-sorter">
	
	<!-- <li class="indiv-widget">
		<div class="widget-topper"></div>
		<div class="widget-content">
			<%= render 'layouts/sidebar_email_form' %>
		</div>
		<div class="widget-bottom"></div>
	</li>	 -->	

	<% @widgets.each do |f| %>
		<li class="indiv-widget">
			<div class="widget-topper"></div>
			<div class="widget-content">				
				
				<% if @widget_order == "current_deal_order" %>
					<%= hidden_field_tag "order[]", "#{f.id},#{f.current_deal_order}", :class => "widget_order_input" %>
				<% end %>
				<% if @widget_order == "recent_deal_order" %>
					<%= hidden_field_tag "order[]", "#{f.id},#{f.recent_deal_order}", :class => "widget_order_input" %>
				<% end %>
				<% if @widget_order == "for_business_order" %>
					<%= hidden_field_tag "order[]", "#{f.id},#{f.for_business_order}", :class => "widget_order_input" %>
				<% end %>
				<% if @widget_order == "contact_order" %>
					<%= hidden_field_tag "order[]", "#{f.id},#{f.contact_order}", :class => "widget_order_input" %>
				<% end %>
				<% if @widget_order == "privacy_policy_order" %>
					<%= hidden_field_tag "order[]", "#{f.id},#{f.privacy_policy_order}", :class => "widget_order_input" %>
				<% end %>
				<% if @widget_order == "terms_of_service_order" %>
					<%= hidden_field_tag "order[]", "#{f.id},#{f.terms_of_service_order}", :class => "widget_order_input" %>
				<% end %>
				
				
				<% unless f.text_1 == nil || f.text_1.empty? %>
					<%= f.text_1.html_safe %>
				<% end %>
				<% if f.widget_image? %>
					<%= image_tag f.widget_image.url(:side_bar), :class => 'widget-image' %>
				<% end %>
				<% if f.title %>
					<h3 class="widget-title"><%= f.title %></h3>
				<% end %>
				<% if f.text_2 %>
					<span class="widget-text"><%= f.text_2.html_safe %></span>
				<% end %>
				<% if f.bottom_title %>
					<span class="minor-widget-text"><%= f.bottom_title %></span>
				<% end %>
			</div>
			<div class="widget-bottom"></div>
		</li>
	<% end %>		
</ul>

<%= submit_tag "Save Widgets", :disable_with => "Please wait...", :class => "widget-submit-btn" %>
<% end %>
<!-- END OF LOGGED IN WIDGET VIEWS -->
	
	<% else %>

<!-- NOT LOGGED IN WIDGET VIEWS -->	
	<ul id="sidebar">
		<% @widgets.each do |f| %>
		<li class="indiv-widget">
			<div class="widget-topper"></div>
			<div class="widget-content">
				<% unless f.text_1 == nil || f.text_1.empty? %>
					<%= f.text_1.html_safe %>
				<% end %>
				<% if f.widget_image? %>
					<%= image_tag f.widget_image.url(:side_bar), :class => 'widget-image' %>
				<% end %>
				<% if f.title %>
					<h3 class="widget-title"><%= f.title %></h3>
				<% end %>
				<% if f.text_2 %>
					<span class="widget-text"><%= f.text_2.html_safe %></span>
				<% end %>
				<% if f.bottom_title %>
					<span class="minor-widget-text"><%= f.bottom_title %></span>
				<% end %>
			</div>
			<div class="widget-bottom"></div>
		</li>	
		<% end %>
	</ul>

<% end %>
	

app/views/layouts/application.html.erb
<!--
	TODO System Wide Notifications
	FIXME Duplicate Widgets
-->

<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  	<%= stylesheet_link_tag :all %>
 	<%= javascript_include_tag :defaults, 'jquery', 'jquery-ui', 'global', 'mbScrollable' %>
	<script src='https://www.dealcurrent.com/embed?publisherID=232'></script>
	<% if @loaddc == "true" %>
		<script src="https://s3.amazonaws.com/media.collarfree.com/dealcurrent/js/userwidget.js"></script>
	<% end %>
	<script>
  		function DCLoginListener(user)
		  {
		    if(!user)
		    {
		       document.getElementById("mydeals").style.display="none";
		       document.getElementById("login").innerHTML = "<a class=\"not-logged-in\" href=\"javascript: return false;\" onclick=\"javascript:ShowDCLogin();\"> Log In or Sign Up </a>";       
		    }
		    else {
				document.getElementById("mydeals").style.display="inline";	       
		       	document.getElementById("login").innerHTML = "<a class=\"logged-in\" href=\"#\" onclick=\"javascript:DCLogout();\"> Log Out </a>";
		    	}
		  	}
		</script>
  <%= csrf_meta_tag %>
  <%= include_tiny_mce_if_needed %>

<meta property="og:title" content="Big Block Deals"/>
<meta property="og:type" content="website"/>
<meta property="og:image" content="http://beta.bigblockdeals.com/images/logo.png"/> 
<meta property="og:url" content="http://beta.bigblockdeals.com"/>
<meta property="og:site_name" content="http://beta.bigblockdeals.com"/>
<meta property="fb:admins" content="79101265">
<meta property="og:description"
          content="Big Block Deals has you covered from lawn services to computer repair. We find the best and bring them to you through amazing offers in your daily deals.<br></br>
		So, if you need to get that fence fixed, find a new pet sitter or get that drain unclogged let us bring great people and deals your way."/>

</head>
<body>
	<%= render 'layouts/admin_nav' %>

	<%= render 'layouts/flash_messages' %>

	<%= render  'layouts/navigation' %>

	<div id="greater-container">
		<div id="container">
			<div id="social-links">
				<a id="twitter-icon" target="blank" href="http://twitter.com/bigblockdeals"></a>
				<div id="fb-root"></div>
				<script>(function(d){
				  var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
				  js = d.createElement('script'); js.id = id; js.async = true;
				  js.src = "//connect.facebook.net/en_US/all.js#appId=245265552184407&xfbml=1";
				  d.getElementsByTagName('head')[0].appendChild(js);
				}(document));</script>
				<div class="fb-like" data-href="beta.bigblockdeals.com" data-send="true" data-layout="button_count" data-width="225" data-show-faces="false"></div>
			</div>
			
			<%= render 'layouts/quotes' %>
			
			<div class="content <%= @layout %>">
				<div class="topper"></div>
				<div class="main-content">
					<%= yield %>
				</div>
				<div class="bottom"></div>
			</div>

			<% if @layout == 'three-fourths' || @layout == 'mostly-text' || @layout =='blog' %>
				<%= render 'layouts/sidebar' %>
			<% end %>

		</div>
	</div>

	<%= render 'layouts/footer' %>


<!--  GOOGLE ANALYTICS  -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-25592624-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- END GOOGLE ANALYTICS -->

</body>
</html>
<%= debug(params) if Rails.env.development? %>